# Generated by Django 5.1.6 on 2025-03-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("user", "User"), ("therapist", "Therapist")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "licence_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "consultation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                (
                    "wellbeing_goal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("feelings", models.JSONField(blank=True, default=dict)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_submission_date", models.DateField(blank=True, null=True)),
                ("mood_ratings", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MoodRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mood", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.signup"
                    ),
                ),
            ],
        ),
    ]
