# Generated by Django 5.1.6 on 2025-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="name",
        ),
        migrations.AddField(
            model_name="login",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="login",
            name="consultation_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="login",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="login",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="login",
            name="feelings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="login",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="login",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="login",
            name="licence_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="login",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("user", "User"), ("therapist", "Therapist")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="username",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name="login",
            name="wellbeing_goal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=150),
        ),
    ]
