# Generated by Django 5.1.7 on 2025-03-19 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("selected_username", models.CharField(max_length=255)),
                ("sent_text", models.TextField(blank=True, null=True)),
                ("received_text", models.TextField(blank=True, null=True)),
                ("text_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelTable(
            name="savedtext",
            table=None,
        ),
    ]
