# Generated by Django 5.1.6 on 2025-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_login_name_login_about_me_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("user", "User"), ("therapist", "Therapist")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "licence_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "consultation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                (
                    "wellbeing_goal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("feelings", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name="Login",
        ),
    ]
