# Generated by Django 5.1.7 on 2025-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chatmessage_alter_savedtext_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="text_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
