# Generated by Django 5.0.6 on 2025-03-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastLogin',
        ),
    ]
