# Generated by Django 5.1.7 on 2025-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_chatmessage_text_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedtext",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
