# Generated by Django 5.1.6 on 2025-03-18 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_signup_current_streak_signup_last_submission_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignIn",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name="moodrating",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="moodrating",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="moodrating",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="feelings",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="last_submission_date",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="longest_streak",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="password",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="username",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="wellbeing_goal",
        ),
        migrations.AddField(
            model_name="moodrating",
            name="angry",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="bored",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="excited",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="happy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="nervous",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="sad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moodrating",
            name="worried",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MoodStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_submission_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.signin"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="signup",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.signin",
            ),
        ),
        migrations.AlterField(
            model_name="moodrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.signin"
            ),
        ),
    ]
